services:
  ubuntu-novnc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-desktop
    restart: unless-stopped
    ports:
      - "6080:8080"
      - "5900:5900"
    environment:
      - RESOLUTION=1600x900x24
      - VNC_PORT=5900
      - NOVNC_PORT=8080
    volumes:
      - ./shared:/home/ubuntu/shared
    networks:
      - ubuntu-net

networks:
  ubuntu-net:
    driver: bridge